# ==========================================
# ç«™ç‚¹åŸºæœ¬ä¿¡æ¯ 
# ==========================================
site_name: é•œç¥çš„çŸ¥è¯†ç½‘ç»œ
site_description: è¿æ¥æ€ç»´çš„èŠ‚ç‚¹ï¼Œæ„å»ºç¬¬äºŒå¤§è„‘

# éƒ¨ç½²åœ°å€ï¼š
site_url: https://qingyaozhuozhang.github.io/
# æºç ä»“åº“åœ°å€ï¼š
repo_url: https://github.com/qingyaozhuozhang/qingyaozhuozhang.github.io
repo_name: GitHub

# ==========================================
# ä¸»é¢˜é…ç½®
# ===================================
theme:
  name: material
  language: zh
  # logo: assets/logo.png
  # favicon: assets/favicon.png

  features:
    - navigation.tabs        
    - navigation.tabs.sticky 
    - navigation.sections    
    - navigation.expand      
    - navigation.top         
    - navigation.tracking    
    - navigation.indexes     
    - toc.follow             
    - search.suggest         
    - search.highlight       
    - content.code.copy      
    - content.action.edit    

  palette:
    # äº®è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white         
      accent: indigo         
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æ·±è‰²æ¨¡å¼

    # æ·±è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate          
      primary: black         
      accent: teal           
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢è‡³äº®è‰²æ¨¡å¼

  font:
    text: Noto Sans SC
    code: JetBrains Mono     

# ===================================
# æ’ä»¶é…ç½®
# ==========================================
plugins:
  - search
  - git-revision-date-localized:
      type: date             
      locale: zh             
      enable_creation_date: false # åªæ˜¾ç¤ºæœ€åæ›´æ–°æ—¥æœŸ
      fallback_to_build_date: true 
  - minify:                  
      minify_html: true

# ==========================================
# Markdown æ‰©å±•
# ===================================
markdown_extensions:
  - admonition               
  - pymdownx.details         
  - attr_list                
  - md_in_html
  - pymdownx.superfences:    
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:      
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:       
      custom_checkbox: true
  - pymdownx.arithmatex:     
      generic: true
  - pymdownx.emoji:          
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# ==========================================
# é¢å¤–è„šæœ¬
# ==========================================
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# ==========================================
# å¯¼èˆªç»“æ„
# ==========================================
nav:
  - ğŸ  é¦–é¡µ: index.md
  - ğŸ§  æ ¸å¿ƒçŸ¥è¯†:
      - ç¼–ç¨‹:
          - è§†è§‰:
            - æ·±åº¦å­¦ä¹ :
              - çŸ¥è¯†ç‚¹: è§†è§‰/æ·±åº¦å­¦ä¹ /çŸ¥è¯†ç‚¹.md
              - å®è·µç»“æœ: è§†è§‰/æ·±åº¦å­¦ä¹ /å®è·µç»“æœ.md
          - å¯¼èˆª:
            - é›·è¾¾:
              - Mid-360æ¿€å…‰é›·è¾¾é…ç½®æ•™ç¨‹: navigation/lidar/Mid-360æ¿€å…‰é›·è¾¾é…ç½®æ•™ç¨‹.md
              - é›·è¾¾å®šä½ä¿¡æ¯: navigation/lidar/é›·è¾¾å®šä½ä¿¡æ¯.md
            - ROS2:
              - å¯¼èˆªä¸»çº¿:
                - ROS2ä¸»æµç¨‹: navigation/ROS2/å¯¼èˆª_ä¸»çº¿/ROS2ä¸»æµç¨‹.md
                - Navigation2å¯¼èˆªæ¡†æ¶: navigation/ROS2/å¯¼èˆª_ä¸»çº¿/Navigation2å¯¼èˆªæ¡†æ¶.md
                - åŒ—æç†ŠNav2æ¡†æ¶: navigation/ROS2/å¯¼èˆª_ä¸»çº¿/åŒ—æç†ŠNav2æ¡†æ¶.md
              - å¯¼èˆªæ”¯çº¿:
                - ROS2åŸºç¡€ç¼–ç¨‹: navigation/ROS2/å¯¼èˆª_æ”¯çº¿/ROS2åŸºç¡€ç¼–ç¨‹.md
                - ROS2å¸¸ç”¨å¼€å‘å·¥å…·: navigation/ROS2/å¯¼èˆª_æ”¯çº¿/ROS2å¸¸ç”¨å¼€å‘å·¥å…·.md
                - launchæ–‡ä»¶çš„ç¼–å†™: navigation/ROS2/å¯¼èˆª_æ”¯çº¿/launchæ–‡ä»¶çš„ç¼–å†™.md
                - ç±»çš„å°è£…å’Œè°ƒç”¨: navigation/ROS2/å¯¼èˆª_æ”¯çº¿/ç±»çš„å°è£…å’Œè°ƒç”¨.md
  - ğŸ› ï¸ æ—¥å¸¸å·¥å…·æ‰©å±•:
      - å·¥å…·é“¾æ¥: æ—¥å¸¸å·¥å…·æ‰©å±•/å·¥å…·é“¾æ¥.md
      - çŸ¥è¯†æ€§èµ„æ–™é“¾æ¥: æ—¥å¸¸å·¥å…·æ‰©å±•/çŸ¥è¯†æ€§èµ„æ–™é“¾æ¥.md
  - ğŸ’­ å¸¸ç”¨ä¾‹ç¨‹:
      - ç”Ÿæ´»å¸¸ç”¨ä¾‹ç¨‹:
        - gitä¸Šä¼ Githubè¿œç¨‹ä»“åº“: å¸¸ç”¨ä¾‹ç¨‹/ç”Ÿæ´»å¸¸ç”¨ä¾‹ç¨‹/git.md
        - åˆ›å»ºGithub_Pageç½‘é¡µèµ„æ–™åº“: å¸¸ç”¨ä¾‹ç¨‹/ç”Ÿæ´»å¸¸ç”¨ä¾‹ç¨‹/Github_Page.md
      - ç¼–ç¨‹å¸¸ç”¨ä¾‹ç¨‹:
        - å¾…æ›´æ–°ï¼šå¸¸ç”¨ä¾‹ç¨‹/ç¼–ç¨‹å¸¸ç”¨ä¾‹ç¨‹/index.md
